name: Lint

on:
  push:
    paths-ignore:
      - "**.md"

# Ref:
#   https://golangci-lint.run/usage/install/#github-actions
#   https://github.com/golangci/golangci-lint-action/tree/ce06d75c9460beadedb35d225c50712eafd16ffb#how-to-use

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Print the version
        run: echo 'golangci-lint: v1.29'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          # skip-go-installation: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
